# Generated by Django 3.0.3 on 2020-03-26 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50)),
                ('sum_grade', models.FloatField(default=0, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('budget', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.FloatField(default=0, max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Assignee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Project')),
            ],
        ),
    ]
