# Generated by Django 3.0.3 on 2020-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0003_auto_20200312_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
