# Generated by Django 3.0.3 on 2020-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0004_auto_20200312_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['project']},
        ),
        migrations.AddField(
            model_name='cost',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
