# Generated by Django 3.0.3 on 2020-03-18 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0006_auto_20200313_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='progress',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='executor',
        ),
        migrations.AddField(
            model_name='job',
            name='assignee',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
