# Generated by Django 3.0.3 on 2020-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0007_auto_20200318_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
