# Generated by Django 3.0.3 on 2020-03-11 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0007_auto_20200310_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='ratio',
            field=models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='progress',
            field=models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
