# Generated by Django 3.0.3 on 2020-03-11 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0008_auto_20200311_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='ratio',
            field=models.PositiveIntegerField(blank=True, default='', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
