# Generated by Django 3.0.3 on 2020-03-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0009_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
