# Generated by Django 3.0.3 on 2020-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0010_remove_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
