# Generated by Django 3.0.3 on 2020-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0011_auto_20200318_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.TextField(null=True),
        ),
    ]
