# Generated by Django 3.0.3 on 2020-03-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0013_auto_20200318_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.CharField(default='', max_length=50),
        ),
    ]
