# Generated by Django 3.0.3 on 2020-03-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0014_auto_20200319_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
