# Generated by Django 3.0.3 on 2020-03-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0015_auto_20200319_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobdivision',
            name='executor',
        ),
        migrations.AddField(
            model_name='jobdivision',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Assignee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Assignee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='AGL_TGGS.Assignee'),
        ),
    ]
