# Generated by Django 3.0.3 on 2020-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0017_auto_20200319_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
