# Generated by Django 3.0.3 on 2020-03-20 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AGL_TGGS', '0021_auto_20200319_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Assignee'),
        ),
        migrations.AlterField(
            model_name='jobdivision',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AGL_TGGS.Assignee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='AGL_TGGS.Assignee'),
        ),
    ]
