# Generated by Django 3.0.3 on 2020-03-20 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AGL_TGGS', '0022_auto_20200320_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
